apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-catalog-api-deployment
  labels:
    app: fiap-catalog-api
spec:
  replicas: 2 # Define a quantidade de réplicas/pods desejada
  selector:
    matchLabels:
      app: fiap-catalog-api
  template:
    metadata:
      labels:
        app: fiap-catalog-api
    spec:
      containers:
      - name: fiap-catalog-api
        image: rodrigosiqsilva/fiap-catalog-api:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 4040
        - name: https
          containerPort: 4041
        resources:
          # Define limites de recursos recomendados para uma aplicação .NET padrão
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Production"
        # O ASPNETCORE_URLS garante que a aplicação escute nas portas expostas pelo Dockerfile
        - name: ASPNETCORE_URLS
          value: "http://+:4040;https://+:4041" 

---

apiVersion: v1
kind: Service
metadata:
  name: fiap-catalog-api-service
  labels:
    app: fiap-catalog-api
spec:
  type: ClusterIP # Altere para LoadBalancer se precisar expor diretamente para a internet
  selector:
    app: fiap-catalog-api
  ports:
  - name: http
    port: 4040
    targetPort: 4040
  - name: https
    port: 4041
    targetPort: 4041